### 闭包、作用域等

#### 不起眼的开始

```js
for (var i = 0; i < 5; i++) {
    setTimeout(function() {
        console.log(new Date, i);
    }, 1000);
}

console.log(new Date, i);
```

分析它实际运行的结果 给出结果：`5,5,5,5,5,5`

```js
2017-03-18T00:43:45.873Z 5
2017-03-18T00:43:46.866Z 5
2017-03-18T00:43:46.868Z 5
2017-03-18T00:43:46.868Z 5
2017-03-18T00:43:46.868Z 5
2017-03-18T00:43:46.868Z 5
```

#### 提问1

**用箭头表示其前后的两次输出之间有 1 秒的时间间隔，而逗号表示其前后的两次输出之间的时间间隔可以忽略**

```js
5 -> 5,5,5,5,5，即第 1 个 5 直接输出，1 秒之后，输出 5 个 5
```

循环执行过程中，几乎同时设置了 5 个定时器，一般情况下，这些定时器都会在 1 秒之后触发，而循环完的输出是立即执行的

#### 追问1：闭包

如果期望代码的输出变成：`5 -> 0,1,2,3,4`，该怎么改造代码？

**解法1：**

```js
for (var i = 0; i < 5; i++) {
    (function(j) {  // j = i
        setTimeout(function() {
            console.log(new Date, j);
        }, 1000);
    })(i);
}

console.log(new Date, i);
```

巧妙的利用 [IIFE](https://link.juejin.cn/?target=http%3A%2F%2Fbenalman.com%2Fnews%2F2010%2F11%2Fimmediately-invoked-function-expression%2F%23iife)（Immediately Invoked Function Expression：声明即执行的函数表达式）来解决闭包造成的问题

**解法2：**

```js
for (var i = 0; i < 5; i++) {
    setTimeout(function(j) {
        console.log(new Date, j);
    }, 1000, i);
}

console.log(new Date, i);
```

**解法3：**利用 JS 中基本类型（Primitive Type）的参数传递是[按值传递](https://link.juejin.cn/?target=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F6605640%2Fjavascript-by-reference-vs-by-value)（Pass by Value）的特征

```js
var output = function (i) {
    setTimeout(function() {
        console.log(new Date, i);
    }, 1000);
};

for (var i = 0; i < 5; i++) {
    output(i);  // 这里传过去的 i 值被复制了
}

console.log(new Date, i);
```

**解法4**：ES6 [块级作用域](https://link.juejin.cn/?target=https%3A%2F%2Fdeveloper.mozilla.org%2Fen%2Fdocs%2FWeb%2FJavaScript%2FReference%2FStatements%2Flet)（Block Scope）中的 `let` 替代了 `var`

```js
for (let i = 0; i < 5; i++) {
    setTimeout(function() {
        console.log(new Date, i);
    }, 1000);
}

console.log(new Date, i);
```

代码在实际运行时会报错，因为最后那个输出使用的 `i` 在其所在的作用域中并不存在，`i` 只存在于循环内部

#### 追问 2：ES6

如果期望代码的输出变成 `0 -> 1 -> 2 -> 3 -> 4 -> 5`，并且要求原有的代码块中的循环和两处 `console.log` 不变，该怎么改造代码？

精确的描述为：代码执行时，立即输出 0，之后每隔 1 秒依次输出 `1,2,3,4`，循环结束后在大概第 5 秒的时候输出 5

```js
const tasks = []; // 这里存放异步操作的 Promise
const output = (i) => new Promise((resolve) => {
    setTimeout(() => {
        console.log(new Date, i);
        resolve();
    }, 1000 * i);
});

// 生成全部的异步操作
for (var i = 0; i < 5; i++) {
    tasks.push(output(i));
}

// 异步操作完成之后，输出最后的 i
Promise.all(tasks).then(() => {
    setTimeout(() => {
        console.log(new Date, i);
    }, 1000);
});
```

使用 Promise 处理异步代码比回调机制让代码可读性更高，但是使用 Promise 的问题也很明显，即如果没有处理 Promise 的 reject，会导致错误被[丢进黑洞](https://link.juejin.cn/?target=http%3A%2F%2Fblog.rangle.io%2Ferrors-in-promises%2F)

#### 追问 3：ES7 

如何使用 ES7 中的 [`async/await`](https://link.juejin.cn/?target=https%3A%2F%2Fdeveloper.mozilla.org%2Fen-US%2Fdocs%2FWeb%2FJavaScript%2FReference%2FStatements%2Fasync_function) 特性来让这段代码变的更简洁？

```js
// 模拟其他语言中的 sleep，实际上可以是任何异步操作
const sleep = (timeountMS) => new Promise((resolve) => {
    setTimeout(resolve, timeountMS);
});

(async () => {  // 声明即执行的 async 函数表达式
    for (var i = 0; i < 5; i++) {
        if (i > 0) {
            await sleep(1000);
        }
        console.log(new Date, i);
    }

    await sleep(1000);
    console.log(new Date, i);
})();
```

### Promise

#### 题目一

```js
const promise = new Promise((resolve, reject) => {
  console.log(1)
  resolve()
  console.log(2)
})
promise.then(() => {
  console.log(3)
})
console.log(4)
```

运行结果：

```js
1
2
4
3
```

解释：Promise 构造函数是同步执行的，`promise.then` 中的函数是异步执行的。

#### 题目二

```js
const promise1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve('success')
  }, 1000)
})
const promise2 = promise1.then(() => {
  throw new Error('error!!!')
})

console.log('promise1', promise1)
console.log('promise2', promise2)

setTimeout(() => {
  console.log('promise1', promise1)
  console.log('promise2', promise2)
}, 2000)
```

运行结果：

```js
promise1 Promise { <pending> }
promise2 Promise { <pending> }
(node:50928) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: error!!!
(node:50928) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
promise1 Promise { 'success' }
promise2 Promise {
  <rejected> Error: error!!!
    at promise.then (...)
    at <anonymous> }
```

解释：promise 有 3 种状态：`pending`、`fulfilled` 或 `rejected`。状态改变只能是 pending->fulfilled 或者 pending->rejected，状态一旦改变则不能再变。上面 promise2 并不是 promise1，而是返回的一个新的 Promise 实例。

#### 题目三

```JS
const promise = new Promise((resolve, reject) => {
  resolve('success1')
  reject('error')
  resolve('success2')
})

promise
  .then((res) => {
    console.log('then: ', res)
  })
  .catch((err) => {
    console.log('catch: ', err)
  })
```

运行结果：

```js
then: success1
```

解释：`构造函数中的 resolve 或 reject 只有第一次执行有效，多次调用没有任何作用`，呼应代码二结论：promise 状态一旦改变则不能再变。

#### 题目四

```js
Promise.resolve(1)
  .then((res) => {
    console.log(res)
    return 2
  })
  .catch((err) => {
    return 3
  })
  .then((res) => {
    console.log(res)
  })
```

运行结果：

```js
1
2
```

解释：promise 可以链式调用。提起链式调用我们通常会想到通过 `return this` 实现，不过 Promise 并不是这样实现的。promise 每次调用 `.then` 或者 `.catch` 都会返回一个新的 promise，从而实现了链式调用。

#### 题目五

```js
const promise = new Promise((resolve, reject) => {
  setTimeout(() => {
    console.log('once')
    resolve('success')
  }, 1000)
})

const start = Date.now()
promise.then((res) => {
  console.log(res, Date.now() - start)
})
promise.then((res) => {
  console.log(res, Date.now() - start)
})
```

运行结果：

```js
once
success 1005
success 1007
```

解释：promise 的 `.then` 或者 `.catch` 可以被调用多次，但这里 Promise 构造函数只执行一次。或者说 promise 内部状态一经改变，并且有了一个值，那么后续每次调用 `.then` 或者 `.catch` 都会直接拿到该值。

#### 题目六

```js
Promise.resolve()
  .then(() => {
    return new Error('error!!!')
  })
  .then((res) => {
    console.log('then: ', res)
  })
  .catch((err) => {
    console.log('catch: ', err)
  })
```

运行结果：

```js
then: Error: error!!!
    at Promise.resolve.then (...)
    at ...
```

解释：`.then` 或者 `.catch` 中 return 一个 error 对象并不会抛出错误，所以不会被后续的 `.catch` 捕获，需要改成其中一种：

```js
return Promise.reject(new Error('error!!!'))
throw new Error('error!!!')
```

因为返回任意一个非 promise 的值都会被包裹成 promise 对象，即 `return new Error('error!!!')` 等价于 `return Promise.resolve(new Error('error!!!'))`。

#### 题目七

```js
const promise = Promise.resolve()
  .then(() => {
    return promise
  })
promise.catch(console.error)
```

运行结果：

```js
TypeError: Chaining cycle detected for promise #<Promise>
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
```

解释：`.then` 或 `.catch` 返回的值不能是 promise 本身，否则会造成死循环。类似于：

```js
process.nextTick(function tick () {
  console.log('tick')
  process.nextTick(tick)
})
```

#### 题目八

```js
Promise.resolve(1)
  .then(2)
  .then(Promise.resolve(3))
  .then(console.log)
```

运行结果：

```js
1
```

解释：`.then` 或者 `.catch` 的参数期望是函数，传入非函数则会发生值穿透。

#### 题目九

```js
Promise.resolve()
  .then(function success (res) {
    throw new Error('error')
  }, function fail1 (e) {
    console.error('fail1: ', e)
  })
  .catch(function fail2 (e) {
    console.error('fail2: ', e)
  })
```

运行结果：

```js
fail2: Error: error
    at success (...)
    at ...
```

解释：`.then` 可以接收两个参数，第一个是处理成功的函数，第二个是处理错误的函数。`.catch` 是 `.then` 第二个参数的简便写法，但是它们用法上有一点需要注意：`.then` 的第二个处理错误的函数捕获不了第一个处理成功的函数抛出的错误，而后续的 `.catch` 可以捕获之前的错误。当然以下代码也可以：

```js
Promise.resolve()
  .then(function success1 (res) {
    throw new Error('error')
  }, function fail1 (e) {
    console.error('fail1: ', e)
  })
  .then(function success2 (res) {
  }, function fail2 (e) {
    console.error('fail2: ', e)
  })
```

#### 题目十

```js
process.nextTick(() => {
  console.log('nextTick')
})
Promise.resolve()
  .then(() => {
    console.log('then')
  })
setImmediate(() => {
  console.log('setImmediate')
})
console.log('end')
```

运行结果：

```js
end
nextTick
then
setImmediate
```

解释：`process.nextTick` 和 `promise.then` 都属于 microtask，而 `setImmediate` 属于 macrotask，在事件循环的 check 阶段执行。事件循环的每个阶段（macrotask）之间都会执行 microtask，事件循环的开始会先执行一次 microtask。
